services:
  
  zigbee2mqtt-01:
    image: ghcr.io/koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt-01
    
    labels:
      # Set of labels for mqtt traffic:
      - traefik.enable=true
      - traefik.tcp.routers.zigbee2mqtt-01.rule=HostSNI(`*`)        # catches all (no SNI-based routing needed for plain TCP)
      - traefik.tcp.routers.zigbee2mqtt-01.entrypoints=zigbee2mqtt-01   # your custom entrypoint
      - traefik.tcp.routers.zigbee2mqtt-01.service=zigbee2mqtt-01-svc
      - traefik.tcp.services.zigbee2mqtt-01-svc.loadbalancer.server.port=6638  # internal TCP port where Z2M container listens for serial
      # Set of labels for http traffic (Z2M dashboard):
      - traefik.http.routers.zigbee2mqtt-01.rule=Host(`${Z2M-01_URL}`)
      - traefik.http.routers.zigbee2mqtt-01.entrypoints=websecure
      - traefik.http.routers.zigbee2mqtt-01.tls.certresolver=letsencrypt
      - traefik.http.services.zigbee2mqtt-01.loadbalancer.server.port=8080    # Internal HTTP port for dashboard
      - traefik.docker.network=vps-stack_traefik-z2m-net

    volumes:
      - /opt/docker/vps-stack/zigbee2mqtt-01/data:/app/data
    environment:
      - TZ=${TZ}
    depends_on:
      - mqtt-broker
    networks:
      traefik-z2m-net:
        ipv4_address: 192.168.1.3
      z2m-mqtt-net:
        ipv4_address: 192.168.2.3  
    restart: unless-stopped


  zigbee2mqtt-02:
    image: ghcr.io/koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt-02
    
    labels:
      # Set of labels for mqtt traffic:
      - traefik.enable=true
      - traefik.tcp.routers.zigbee2mqtt-02.rule=HostSNI(`*`)        # catches all (no SNI-based routing needed for plain TCP)
      - traefik.tcp.routers.zigbee2mqtt-02.entrypoints=zigbee2mqtt-02   # your custom entrypoint
      - traefik.tcp.routers.zigbee2mqtt-02.service=zigbee2mqtt-02-svc
      - traefik.tcp.services.zigbee2mqtt-02-svc.loadbalancer.server.port=6639  # internal TCP port where Z2M container listens for serial
      # Set of labels for http traffic (Z2M dashboard):
      - traefik.http.routers.zigbee2mqtt-02.rule=Host(`${Z2M-02_URL}`)
      - traefik.http.routers.zigbee2mqtt-02.entrypoints=websecure
      - traefik.http.routers.zigbee2mqtt-02.tls.certresolver=letsencrypt
      - traefik.http.services.zigbee2mqtt-02.loadbalancer.server.port=8080    # Internal HTTP port for dashboard
      - traefik.docker.network=vps-stack_traefik-z2m-net

    volumes:
      - /opt/docker/vps-stack/zigbee2mqtt-02/data:/app/data
    environment:
      - TZ=${TZ}
    depends_on:
      - mqtt-broker
    networks:
      traefik-z2m-net:
        ipv4_address: 192.168.1.4
      z2m-mqtt-net:
        ipv4_address: 192.168.2.4
    restart: unless-stopped

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    # labels:  # Use the traefik labels only if MQTT comes from traefik; otherwise comment out
    # - traefik.http.routers.mqtt.rule=Host(`${MQTT_URL}`)
    # - traefik.http.routers.mqtt.entrypoints=websecure
    # - traefik.http.routers.mqtt.tls.certresolver=letsencrypt
    ports:
      - "8883:8883"   # TLS MQTT (recommended for secure usage, use "1883:1883" for plain MQTT)
    volumes: 
      - /opt/docker/vps-stack/mosquitto/config:/mosquitto/config
      - /opt/docker/vps-stack/mosquitto/data:/mosquitto/data
      - /opt/docker/vps-stack/mosquitto/log:/mosquitto/log
    networks:
      z2m-mqtt-net:
        ipv4_address: 192.168.2.2
      mqtt-ha-net:
        ipv4_address: 192.168.3.2
    restart: unless-stopped


  acme:   # ACME protocol client, used to issue + renew certificates
    image: neilpang/acme.sh
    container_name: acme-mqtt
    restart: unless-stopped
    env_file:
      - /opt/docker/vps-stack/env/acme.env
    volumes:
      - /opt/docker/vps-stack/acme-config:/acme.sh
      - /opt/docker/vps-stack/mosquitto/renew-hook.sh:/renew-hook.sh:ro
      - /opt/docker/vps-stack/mosquitto/config:/mosquitto-config
    command: daemon

  ha01:
    image: homeassistant/home-assistant:stable
    container_name: ha01
    labels:
      - traefik.enable=true
      - traefik.http.routers.ha01.rule=Host(`${HA01_URL}`)
      - traefik.http.routers.ha01.entrypoints=websecure
      - traefik.http.routers.ha01.tls.certresolver=letsencrypt
      - traefik.http.services.ha01.loadbalancer.server.port=8123
      - traefik.docker.network=vps-stack_traefik-ha-net
    volumes:
      - /opt/docker/vps-stack/homeassistant/ha01-config:/config 
    environment:
      - TZ=${TZ}
    networks:
      traefik-ha-net:
        ipv4_address: 192.168.4.3
      mqtt-ha-net:
        ipv4_address: 192.168.3.3

    restart: unless-stopped

  ha02:
    image: homeassistant/home-assistant:stable
    container_name: ha02
    labels:
      - traefik.enable=true
      - traefik.http.routers.ha02.rule=Host(`${HA02_URL}`)
      - traefik.http.routers.ha02.entrypoints=websecure
      - traefik.http.routers.ha02.tls.certresolver=letsencrypt
      - traefik.http.services.ha02.loadbalancer.server.port=8123
      - traefik.docker.network=vps-stack_traefik-ha-net
    volumes:
      - /opt/docker/vps-stack/homeassistant/ha02-config:/config 
    environment:
      - TZ=${TZ}
    networks:
      mqtt-ha-net:
        ipv4_address: 192.168.3.4
      traefik-ha-net:
        ipv4_address: 192.168.4.4
    restart: unless-stopped
