services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    labels:
    - traefik.http.routers.mqtt.rule=Host(`${MQTT_URL}`)
    - traefik.http.routers.mqtt.entrypoints=websecure
    - traefik.http.routers.mqtt.tls.certresolver=letsencrypt
    ports:
      - "1883:1883"   # plain MQTT (keep only if you really need public unauthenticated access)
      - "8883:8883"   # TLS MQTT (recommended for any external/secure usage)
    volumes: 
      - /opt/docker/vps-stack/mosquitto/config:/mosquitto/config
      - /opt/docker/vps-stack/mosquitto/data:/mosquitto/data
      - /opt/docker/vps-stack/mosquitto/log:/mosquitto/log
    networks:
      ha-net:
        ipv4_address: 192.168.0.11
    restart: unless-stopped

  ha01:
    image: homeassistant/home-assistant:stable
    container_name: ha01
    labels:
      - traefik.enable=true
      - traefik.http.routers.ha01.rule=Host(`${HA01_URL}`)
      - traefik.http.routers.ha01.entrypoints=websecure
      - traefik.http.routers.ha01.tls.certresolver=letsencrypt
      - traefik.http.services.ha01.loadbalancer.server.port=8123
    volumes:
      - /opt/docker/vps-stack/homeassistant/ha01-config:/config 
    environment:
      - TZ=${TZ}
    networks:
      ha-net:
        ipv4_address: 192.168.0.101
    restart: unless-stopped

  ha02:
    image: homeassistant/home-assistant:stable
    container_name: ha02
    labels:
      - traefik.enable=true
      - traefik.http.routers.ha02.rule=Host(`${HA02_URL}`)
      - traefik.http.routers.ha02.entrypoints=websecure
      - traefik.http.routers.ha02.tls.certresolver=letsencrypt
      - traefik.http.services.ha02.loadbalancer.server.port=8123
    volumes:
      - /opt/docker/vps-stack/homeassistant/ha02-config:/config 
    environment:
      - TZ=${TZ}
    networks:
      ha-net:
        ipv4_address: 192.168.0.102
    restart: unless-stopped
