services:
  
  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt:latest
    container_name: z2m
    
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.zigbee2mqtt.rule=HostSNI(`*`)        # catches all (no SNI-based routing needed for plain TCP)
      - traefik.tcp.routers.zigbee2mqtt.entrypoints=zigbee2mqtt   # your custom entrypoint
      - traefik.tcp.routers.zigbee2mqtt.service=zigbee2mqtt-svc
      - traefik.tcp.services.zigbee2mqtt-svc.loadbalancer.server.port=6638  # internal TCP port where Z2M container listens for serial
    
    volumes:
      - /opt/docker/vps-stack/zigbee2mqtt/data:/app/data
    environment:
      - TZ=${TZ}
    depends_on:
      - mqtt-broker
    networks:
      traefik-z2m-net:
        ipv4_address: 192.168.0.3
      z2m-mqtt-net:
        ipv4_address: 192.168.0.10  
 
    restart: unless-stopped

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    # labels:  # Use the traefik labels only if MQTT comes from traefik; otherwise comment out
    # - traefik.http.routers.mqtt.rule=Host(`${MQTT_URL}`)
    # - traefik.http.routers.mqtt.entrypoints=websecure
    # - traefik.http.routers.mqtt.tls.certresolver=letsencrypt
    ports:
      - "8883:8883"   # TLS MQTT (recommended for secure usage, use "1883:1883" for plain MQTT)
    volumes: 
      - /opt/docker/vps-stack/mosquitto/config:/mosquitto/config
      - /opt/docker/vps-stack/mosquitto/data:/mosquitto/data
      - /opt/docker/vps-stack/mosquitto/log:/mosquitto/log
    networks:
      z2m-mqtt-net:
        ipv4_address: 192.168.0.11
      mqtt-ha-net:
        ipv4_address: 192.168.0.18
    restart: unless-stopped

  acme:   # ACME protocol client, used to issue + renew certificates
    image: neilpang/acme.sh
    container_name: acme-mqtt
    restart: unless-stopped
    env_file:
      - /opt/docker/vps-stack/env/acme.env
    volumes:
      - /opt/docker/vps-stack/acme-config:/acme.sh
      - /opt/docker/vps-stack/mosquitto/renew-hook.sh:/renew-hook.sh:ro
      - /opt/docker/vps-stack/mosquitto/config:/mosquitto-config
    command: daemon

  ha01:
    image: homeassistant/home-assistant:stable
    container_name: ha01
    labels:
      - traefik.enable=true
      - traefik.http.routers.ha01.rule=Host(`${HA01_URL}`)
      - traefik.http.routers.ha01.entrypoints=websecure
      - traefik.http.routers.ha01.tls.certresolver=letsencrypt
      - traefik.http.services.ha01.loadbalancer.server.port=8123
    volumes:
      - /opt/docker/vps-stack/homeassistant/ha01-config:/config 
    environment:
      - TZ=${TZ}
    networks:
      mqtt-ha-net:
        ipv4_address: 192.168.0.19
      traefik-ha-net:
        ipv4_address: 192.168.0.27
    restart: unless-stopped

  ha02:
    image: homeassistant/home-assistant:stable
    container_name: ha02
    labels:
      - traefik.enable=true
      - traefik.http.routers.ha02.rule=Host(`${HA02_URL}`)
      - traefik.http.routers.ha02.entrypoints=websecure
      - traefik.http.routers.ha02.tls.certresolver=letsencrypt
      - traefik.http.services.ha02.loadbalancer.server.port=8123
    volumes:
      - /opt/docker/vps-stack/homeassistant/ha02-config:/config 
    environment:
      - TZ=${TZ}
    networks:
      mqtt-ha-net:
        ipv4_address: 192.168.0.20
      traefik-ha-net:
        ipv4_address: 192.168.0.28
    restart: unless-stopped
