services:
  
  z2m-01:
    image: ghcr.io/koenkk/zigbee2mqtt:latest
    container_name: z2m-01
    
    labels:
      # MQTT traffic:
      - traefik.enable=true
      - traefik.tcp.routers.z2m-01-serial.rule=HostSNI(`*`)         # catches all (no SNI-based routing needed for plain TCP)
      - traefik.tcp.routers.z2m-01-serial.entrypoints=z2m-01        # custom entrypoint (on TCP 6001, see traefik configuration)
      - traefik.tcp.routers.z2m-01-serial.service=z2m-01-serial-svc
      - traefik.tcp.services.z2m-01-serial-svc.loadbalancer.server.port=6638  # internal TCP port where z2m-01 container listens to serial traffic
      
      # HTTP dashboard routing + basic auth
      - traefik.http.routers.z2m-01-web.rule=Host(`${Z2M01_URL}`) # && PathPrefix(`/internal`)
      - traefik.http.routers.z2m-01-web.entrypoints=web
      - traefik.http.routers.z2m-01-web.service=z2m-01-web-svc
      - traefik.http.routers.z2m-01-web.middlewares=z2m-01-auth

      # Service port
      - traefik.http.services.z2m-01-web-svc.loadbalancer.server.port=8080

      # Basic Auth middleware
      - traefik.http.middlewares.z2m-01-auth.basicauth.usersfile=/run/secrets/z2m-01-auth

      # Traefik reaches z2m-01 from this network only:
      - traefik.docker.network=vps-stack_traefik-z2m-net

    env_file:
      - /opt/docker/vps-stack/env/z2m.env
    volumes:
      - /opt/docker/vps-stack/zigbee2mqtt/z2m-01:/app/data
    environment:
      - TZ=${TZ}
    depends_on:
      - mqtt-broker
    networks:
      traefik-z2m-net:
        ipv4_address: 192.168.1.3
      z2m-mqtt-net:
        ipv4_address: 192.168.2.3
    extra_hosts:
      - "mqtt.myhomeassistant.app:192.168.2.2"
    restart: unless-stopped


  z2m-02:
    image: ghcr.io/koenkk/zigbee2mqtt:latest
    container_name: z2m-02
    
    labels:
      # MQTT traffic:
      - traefik.enable=true
      - traefik.tcp.routers.z2m-02-serial.rule=HostSNI(`*`)         # catches all (no SNI-based routing needed for plain TCP)
      - traefik.tcp.routers.z2m-02-serial.entrypoints=z2m-02        # custom entrypoint (on TCP 6002 , see traefik configuration)
      - traefik.tcp.routers.z2m-02-serial.service=z2m-02-serial-svc
      - traefik.tcp.services.z2m-02-serial-svc.loadbalancer.server.port=6638  # internal TCP port where z2m-02 container listens to serial traffic

      # HTTP dashboard routing - INTERNAL router (avoids prompting for authentication when requests come from within Home Assistant)
      - traefik.http.routers.z2m-02-web-internal.rule=Host(`${Z2M02_URL}`) && ClientIP(`192.168.4.0/24`)  # traefik-ha-net
      - traefik.http.routers.z2m-02-web-internal.entrypoints=web
      - traefik.http.routers.z2m-02-web-internal.priority=20          # Higher number = higher priority
      - traefik.http.routers.z2m-02-web-internal.service=z2m-02-web-svc

      # HTTP dashboard routing - EXTERNAL router (prompts for authentication when requests come from anywhere else (external URL)
      - traefik.http.routers.z2m-02-web-external.rule=Host(`${Z2M02_URL}`)
      - traefik.http.routers.z2m-02-web-external.entrypoints=web
      - traefik.http.routers.z2m-02-web-external.priority=10          # Lower number = lower priority
      - traefik.http.routers.z2m-02-web-external.service=z2m-02-web-svc
      - traefik.http.routers.z2m-02-web-external.middlewares=z2m-02-auth

      # Service port (shared by both routers "z2m-02-web-internal" and "z2m-02-web-external")
      - traefik.http.services.z2m-02-web-svc.loadbalancer.server.port=8080

      # Basic Auth middleware (still defined once)
      - traefik.http.middlewares.z2m-02-auth.basicauth.usersfile=/run/secrets/z2m-02-auth

      # Traefik reaches z2m-01 from this network only:
      - traefik.docker.network=vps-stack_traefik-z2m-net

    env_file:
      - /opt/docker/vps-stack/env/z2m.env
    volumes:
      - /opt/docker/vps-stack/zigbee2mqtt/z2m-02:/app/data
    environment:
      - TZ=${TZ}
    depends_on:
      - mqtt-broker
    networks:
      traefik-z2m-net:
        ipv4_address: 192.168.1.4
      z2m-mqtt-net:
        ipv4_address: 192.168.2.4
    extra_hosts:
      - "mqtt.myhomeassistant.app:192.168.2.2"
    restart: unless-stopped

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    # labels:  # Use the traefik labels only if MQTT comes from traefik; otherwise comment out
    # - traefik.http.routers.mqtt.rule=Host(`${MQTT_URL}`)
    # - traefik.http.routers.mqtt.entrypoints=websecure
    # - traefik.http.routers.mqtt.tls.certresolver=letsencrypt
    ports:
      - "8883:8883"   # TLS MQTT (recommended for secure usage, use "1883:1883" for plain MQTT)
    volumes: 
      - /opt/docker/vps-stack/mosquitto/config:/mosquitto/config
      - /opt/docker/vps-stack/mosquitto/data:/mosquitto/data
      - /opt/docker/vps-stack/mosquitto/log:/mosquitto/log
    networks:
      z2m-mqtt-net:
        ipv4_address: 192.168.2.2
      mqtt-ha-net:
        ipv4_address: 192.168.3.2
    restart: unless-stopped


  acme:   # ACME protocol client, used to issue + renew certificates
    image: neilpang/acme.sh
    container_name: acme-mqtt
    restart: unless-stopped
    env_file:
      - /opt/docker/vps-stack/env/acme.env
    volumes:
      - /opt/docker/vps-stack/acme-config:/acme.sh
      - /opt/docker/vps-stack/mosquitto/renew-hook.sh:/renew-hook.sh:ro
      - /opt/docker/vps-stack/mosquitto/config:/mosquitto-config
    command: daemon

  ha01:
    image: homeassistant/home-assistant:stable
    container_name: ha01
    labels:
      - traefik.enable=true
      - traefik.http.routers.ha01.rule=Host(`${HA01_URL}`)
      - traefik.http.routers.ha01.entrypoints=web
      - traefik.http.services.ha01.loadbalancer.server.port=8123
      - traefik.docker.network=vps-stack_traefik-ha-net
    volumes:
      - /opt/docker/vps-stack/homeassistant/ha01-config:/config 
    environment:
      - TZ=${TZ}
    networks:
      traefik-ha-net:
        ipv4_address: 192.168.4.3
      mqtt-ha-net:
        ipv4_address: 192.168.3.3
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "mqtt.myhomeassistant.app:192.168.3.2"

    restart: unless-stopped

  ha02:
    image: homeassistant/home-assistant:stable
    container_name: ha02
    labels:
      - traefik.enable=true
      - traefik.http.routers.ha02.rule=Host(`${HA02_URL}`)
      - traefik.http.routers.ha02.entrypoints=web
      - traefik.http.services.ha02.loadbalancer.server.port=8123
      - traefik.docker.network=vps-stack_traefik-ha-net
    volumes:
      - /opt/docker/vps-stack/homeassistant/ha02-config:/config 
    environment:
      - TZ=${TZ}
    networks:
      mqtt-ha-net:
        ipv4_address: 192.168.3.4
      traefik-ha-net:
        ipv4_address: 192.168.4.4
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "mqtt.myhomeassistant.app:192.168.3.2"
    restart: unless-stopped
