services:
  
  z2m-01:
    image: ghcr.io/koenkk/zigbee2mqtt:latest
    container_name: z2m-01
    
    labels:
      # Set of labels for mqtt traffic:
      - traefik.enable=true
      - traefik.tcp.routers.z2m-01-serial.rule=HostSNI(`*`)         # catches all (no SNI-based routing needed for plain TCP)
      - traefik.tcp.routers.z2m-01-serial.entrypoints=z2m-01        # custom entrypoint (on TCP 6001, see traefik configuration)
      - traefik.tcp.routers.z2m-01-serial.service=z2m-01-serial-svc
      - traefik.tcp.services.z2m-01-serial-svc.loadbalancer.server.port=6638  # internal TCP port where z2m-01 container listens to serial traffic
      # Set of labels for http traffic (Z2M dashboard):
      - traefik.http.routers.z2m-01-web.rule=Host(`${HA01_URL}`) && PathPrefix(`${Z2M_PATH}`)
      - traefik.http.routers.z2m-01-web.entrypoints=websecure
      - traefik.http.routers.z2m-01-web.priority=10
      - traefik.http.routers.z2m-01-web.tls=true
      - traefik.http.routers.z2m-01-web.tls.certresolver=letsencrypt
      - traefik.http.routers.z2m-01-web.service=z2m-01-web-svc
      # - traefik.http.routers.z2m-01-web.middlewares=strip-z2m-01  # Attach middleware
      - traefik.http.middlewares.strip-z2m-01.stripprefix.prefixes=/z2m  # Strips /z2m before forwarding
      - traefik.http.services.z2m-01-web-svc.loadbalancer.server.port=8080    # Internal HTTP port for dashboard
      - traefik.docker.network=vps-stack_traefik-z2m-net
      # Redirect "*.myhomeassistant.app/z2m" to "*.myhomeassistant.app/z2m/" (note the trailing "/") 
      - traefik.http.middlewares.z2m-01-redirect.redirectregex.regex=^https?://[^/]+/z2m$
      - traefik.http.middlewares.z2m-01-redirect.redirectregex.replacement=https://${host}/z2m/
      - traefik.http.routers.z2m-01-web.middlewares=strip-z2m-01,z2m-01-redirect    # Attach middlewares

    env_file:
      - /opt/docker/vps-stack/env/z2m.env
    volumes:
      - /opt/docker/vps-stack/zigbee2mqtt/z2m-01:/app/data
    environment:
      - TZ=${TZ}
    depends_on:
      - mqtt-broker
    networks:
      traefik-z2m-net:
        ipv4_address: 192.168.1.3
      z2m-mqtt-net:
        ipv4_address: 192.168.2.3
    extra_hosts:
      - "mqtt.myhomeassistant.app:192.168.2.2"
    restart: unless-stopped


  z2m-02:
    image: ghcr.io/koenkk/zigbee2mqtt:latest
    container_name: z2m-02
    
    labels:
      # Set of labels for mqtt traffic:
      - traefik.enable=true
      - traefik.tcp.routers.z2m-02-serial.rule=HostSNI(`*`)         # catches all (no SNI-based routing needed for plain TCP)
      - traefik.tcp.routers.z2m-02-serial.entrypoints=z2m-02        # custom entrypoint (on TCP 6002 , see traefik configuration)
      - traefik.tcp.routers.z2m-02-serial.service=z2m-02-serial-svc
      - traefik.tcp.services.z2m-02-serial-svc.loadbalancer.server.port=6638  # internal TCP port where z2m-02 container listens to serial traffic
      # Set of labels for http traffic (Z2M dashboard):
      - traefik.http.routers.z2m-02-web.rule=Host(`${HA02_URL}`) && PathPrefix(`${Z2M_PATH}`)
      - traefik.http.routers.z2m-02-web.entrypoints=websecure
      - traefik.http.routers.z2m-02-web.priority=10
      - traefik.http.routers.z2m-02-web.tls=true
      - traefik.http.routers.z2m-02-web.tls.certresolver=letsencrypt
      - traefik.http.routers.z2m-02-web.service=z2m-02-web-svc
      - traefik.http.routers.z2m-02-web.middlewares=strip-z2m-02  # Attach middleware
      - traefik.http.middlewares.strip-z2m-02.stripprefix.prefixes=/z2m  # Strips /z2m before forwarding
      - traefik.http.services.z2m-02-web-svc.loadbalancer.server.port=8080    # Internal HTTP port for dashboard
      - traefik.docker.network=vps-stack_traefik-z2m-net
    env_file:
      - /opt/docker/vps-stack/env/z2m.env
    volumes:
      - /opt/docker/vps-stack/zigbee2mqtt/z2m-02:/app/data
    environment:
      - TZ=${TZ}
    depends_on:
      - mqtt-broker
    networks:
      traefik-z2m-net:
        ipv4_address: 192.168.1.4
      z2m-mqtt-net:
        ipv4_address: 192.168.2.4
    extra_hosts:
      - "mqtt.myhomeassistant.app:192.168.2.2"
    restart: unless-stopped

  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    # labels:  # Use the traefik labels only if MQTT comes from traefik; otherwise comment out
    # - traefik.http.routers.mqtt.rule=Host(`${MQTT_URL}`)
    # - traefik.http.routers.mqtt.entrypoints=websecure
    # - traefik.http.routers.mqtt.tls.certresolver=letsencrypt
    ports:
      - "8883:8883"   # TLS MQTT (recommended for secure usage, use "1883:1883" for plain MQTT)
    volumes: 
      - /opt/docker/vps-stack/mosquitto/config:/mosquitto/config
      - /opt/docker/vps-stack/mosquitto/data:/mosquitto/data
      - /opt/docker/vps-stack/mosquitto/log:/mosquitto/log
    networks:
      z2m-mqtt-net:
        ipv4_address: 192.168.2.2
      mqtt-ha-net:
        ipv4_address: 192.168.3.2
    restart: unless-stopped


  acme:   # ACME protocol client, used to issue + renew certificates
    image: neilpang/acme.sh
    container_name: acme-mqtt
    restart: unless-stopped
    env_file:
      - /opt/docker/vps-stack/env/acme.env
    volumes:
      - /opt/docker/vps-stack/acme-config:/acme.sh
      - /opt/docker/vps-stack/mosquitto/renew-hook.sh:/renew-hook.sh:ro
      - /opt/docker/vps-stack/mosquitto/config:/mosquitto-config
    command: daemon

  ha01:
    image: homeassistant/home-assistant:stable
    container_name: ha01
    labels:
      - traefik.enable=true
      - traefik.http.routers.ha01.rule=Host(`${HA01_URL}`)
      - traefik.http.routers.ha01.entrypoints=websecure
      - traefik.http.routers.ha01.priority=5
      - traefik.http.routers.ha01.tls.certresolver=letsencrypt
      - traefik.http.services.ha01.loadbalancer.server.port=8123
      - traefik.docker.network=vps-stack_traefik-ha-net
    volumes:
      - /opt/docker/vps-stack/homeassistant/ha01-config:/config 
    environment:
      - TZ=${TZ}
    networks:
      traefik-ha-net:
        ipv4_address: 192.168.4.3
      mqtt-ha-net:
        ipv4_address: 192.168.3.3
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "mqtt.myhomeassistant.app:192.168.3.2"

    restart: unless-stopped

  ha02:
    image: homeassistant/home-assistant:stable
    container_name: ha02
    labels:
      - traefik.enable=true
      - traefik.http.routers.ha02.rule=Host(`${HA02_URL}`)
      - traefik.http.routers.ha02.entrypoints=websecure
      - traefik.http.routers.ha02.priority=5
      - traefik.http.routers.ha02.tls.certresolver=letsencrypt
      - traefik.http.services.ha02.loadbalancer.server.port=8123
      - traefik.docker.network=vps-stack_traefik-ha-net
    volumes:
      - /opt/docker/vps-stack/homeassistant/ha02-config:/config 
    environment:
      - TZ=${TZ}
    networks:
      mqtt-ha-net:
        ipv4_address: 192.168.3.4
      traefik-ha-net:
        ipv4_address: 192.168.4.4
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "mqtt.myhomeassistant.app:192.168.3.2"
    restart: unless-stopped
